### PR TITLE
Fix raw-window-handle & many other compilation errors

### PR DESCRIPTION
**Pull request by What42Pizza**
Fix every compilation error I have on windows, including raw-window-handle features.

Biggest problems I can see:
- Example audio-queue-squarewave has effecively been removed (using cfg)
- Example audio-whitespace now uses an Arc<Mutex<>>

### CODE REVIEW

**Comment by revmischa** [comment]
Thank you!

**Comment by What42Pizza** [comment]
I haven't done any testing to make sure that this works as it should, but I can at least confirm that `SDL_PROP_WINDOW_WIN32_INSTANCE_POINTER` seems to be correct (https://docs.rs/sdl3-sys/latest/src/sdl3_sys/generated/video.rs.html#1914)

**Comment by What42Pizza** [comment]
Oh nice you've already merged it, when do you think the next update with this will be released?

**Comment by revmischa** [comment]
just released v0.11.10

**Comment by What42Pizza** [comment]
Thanks!

**Pull request merged**
